project:
  type: website
  #render:
  # - sections.qmd that you want to render
  # - "!directory.qmd" to exlcude a file 

website:
  title: "Sarah Hope"
  navbar:
    background: primary
    search: true
    left:
      - text: Home
        href: index.qmd
      - text: About
        href: about.qmd
      - text: VC
        href: cv.qmd

format:
  html:
    theme:
      - minty
    css: bootstrap.css
    toc: true

editor: visual

